#!/bin/csh

@ count = 1.0

while ($count <= 10)
	rm test-text
	#randgen $count $1 > test-text
	cat test-text
	echo ""
	echo $count
	echo "result pf slp follows:"
	echo "-----"
	echo "result of senkei follows:"
	echo "====="

	@ count += 0.2
end

