LIB = /usr/lib
#LIB = /usr/local/mysql/lib/mysql
INC = /usr/include/mysql
#INC = /usr/local/mysql/include/mysql

all:
	gcc -O -g -o tt timetable_at_Satie.c -R$(LIB) -L$(LIB) -I$(INC) -lmysqlclient -lm #-lz -lnsl -lsocket -lz


