################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
S_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
OBJS := 
C_DEPS := 
LSS := 
S_DEPS := 
CXX_DEPS := 
S_UPPER_DEPS := 
C++_DEPS := 
ASM_DEPS := 
CC_DEPS := 
ARCHIVES := 
CPP_DEPS := 
C_UPPER_DEPS := 
SIZEDUMMY := 

# Every subdirectory with source files must be described here
SUBDIRS := \
libraries/Wire/utility \
libraries/Wire \
libraries/Stepper \
libraries/SoftwareSerial \
libraries/Servo \
libraries/SPI \
libraries/SD/utility \
libraries/SD \
libraries/LiquidCrystal \
libraries/Firmata \
libraries/Ethernet/utility \
libraries/Ethernet \
libraries/EEPROM \
home_libraries/WaveHC \
home_libraries/UsbKeyboard \
home_libraries/UartBridge_SC16IS750 \
home_libraries/USB_Host_Shield \
home_libraries/USB_Host_Shield/examples/HID/le3dp \
home_libraries/USB_Host_Shield/examples/HID/USBHIDJoystick \
home_libraries/TouchScreen \
home_libraries/Tlc5940 \
home_libraries/TimerOne \
home_libraries/TimerCounter \
home_libraries/TextStream \
home_libraries/TFTLCD \
home_libraries/Sparkfun6DOF \
home_libraries/SerialSRAM_SPI \
home_libraries/Sensirion \
home_libraries/SD_SPI/utility \
home_libraries/SD_SPI \
home_libraries/SCP1000D01 \
home_libraries/Roomba500 \
home_libraries/Roomba \
home_libraries/RTC_DS3234 \
home_libraries/RTC_DS1307 \
home_libraries/RFID_StrongLink_UART \
home_libraries/RFID_StrongLink \
home_libraries/RFID_RCS620S \
home_libraries/RFID_PaSoRi \
home_libraries/RFID_PN532_SPI \
home_libraries/RFID_PN532_I2C \
home_libraries/Pololu/PololuWheelEncoders \
home_libraries/Pololu/PololuQTRSensors \
home_libraries/Pololu/Pololu3pi \
home_libraries/Pololu/OrangutanResources \
home_libraries/Pololu/OrangutanPushbuttons \
home_libraries/Pololu/OrangutanMotors \
home_libraries/Pololu/OrangutanLEDs \
home_libraries/Pololu/OrangutanLCD \
home_libraries/Pololu/OrangutanDigital \
home_libraries/Pololu/OrangutanBuzzer \
home_libraries/Pololu/OrangutanAnalog \
home_libraries/OneWireMaster \
home_libraries/OneWire2/examples \
home_libraries/OneWire2 \
home_libraries/OneWire \
home_libraries/NewSoftSerial \
home_libraries/MindSet/mdt/tgcd/win32 \
home_libraries/MindSet/mdt/tg \
home_libraries/MindSet \
home_libraries/MCP23009 \
home_libraries/KeyMatrix \
home_libraries/HMC5843 \
home_libraries/HC595 \
home_libraries/GrLCD12864 \
home_libraries/GPS \
home_libraries/FeliCaPlug \
home_libraries/Fat16 \
home_libraries/Ethernet_w5100/utility \
home_libraries/Ethernet_w5100 \
home_libraries/Digital6DOF \
home_libraries/DataFlash_SPI \
home_libraries/DES_OUTE \
home_libraries/ChibiOS/utility \
home_libraries/ChibiOS/SdFat \
home_libraries/ChibiOS \
home_libraries/ChibiOS/BufferedWriter \
home_libraries/ChLCD_SoftwareSerial \
home_libraries/ChLCD_ST7032i \
home_libraries/ChLCD_MCP2300x \
home_libraries/ChLCD_HC595 \
home_libraries/CapacitiveSense \
home_libraries/CameraC328R \
home_libraries/BMP085 \
home_libraries/BMP085/ATmega328 \
home_libraries/Adafruit_PCD8544_Nokia_LCD \
home_libraries/Adafruit_LED_Backpack \
home_libraries/Adafruit_GFX \
home_libraries/AP_GPS \
home_libraries/APM_Compass \
home_libraries/AFMotor \
home_libraries/AES128 \
home_libraries/ADC_MCP320X \
cores/arduino \
Arduino_sketch_home/sdfatlib20100818/SdFat \
Arduino_sketch_home/hardware/Quaranta/cores/arduino \
Arduino_sketch_home/hardware/Quaranta/bootloaders/atmega644p \
Arduino_sketch_home/hardware/Quaranta/bootloaders/atmega \
Arduino_sketch_home/hardware/ProMicro/cores/arduino \
Arduino_sketch_home/hardware/ProMicro/bootloaders/caterina \
Arduino_sketch_home/a1ronzo-6DOF-Digital-3585b54 \
Arduino_sketch_home/SparkLCD/fromOriginal \
Arduino_sketch_home/SparkLCD \
Arduino_sketch_home/SF9DOF/sketch_dec02a \
Arduino_sketch_home/ChibiOS20120221/originalFiles \
Arduino_sketch_home/ChibiOS20120221/editedFiles \

