
trans_dict = { 'CashAndDeposits': '現金および預金', 
              'NotesAndAccountsReceivableTrade': '受取手形及び売掛金',
              'ElectronicallyRecordedMonetaryClaimsOperatingCA': '電子記録債権',
              'MerchandiseAndFinishedGoods' : '商品及び製品',
              'WorkInProcess' : '仕掛品', 
              'RawMaterialsAndSupplies': '原材料及び貯蔵品', 
              'OtherCA': 'その他流動資産',
              'AllowanceForDoubtfulAccountsCA': '貸倒引当金', 
              'CurrentAssets': '流動資産合計',
              'BuildingsAndStructuresNet': '建物及び構築物（純額）', 
              'MachineryEquipmentAndVehiclesNet': '機械装置及び運搬具（純額）',
              'Land': '土地',
              'OtherNetPPE': 'その他有形固定資産（純額）',
              'PropertyPlantAndEquipment': '有形固定資産合計',
              'OtherIA': 'その他無形固定資産',
              'IntangibleAssets': '無形固定資産合計',
              'GuaranteeDepositsIOA': '差入保証金',
              'OtherIOA': 'その他投資その他の資産',
              'AllowanceForDoubtfulAccountsIOAByGroup': '貸倒引当金',
              'InvestmentsAndOtherAssets': '投資その他の資産合計',
              'NoncurrentAssets': '固定資産合計',
              'Assets': '資産合計',
              'NotesAndAccountsPayableTrade': '支払手形及び買掛金',
              'ElectronicallyRecordedObligationsOperatingCL': '電子記録債務',
              'CurrentLiabilities': '流動負債合計',
              'LongTermLoansPayable': '長期借入金',
              'ShortTermLoansPayable': '短期借入金',
              'CurrentPortionOfLongTermLoansPayable': '1年内返済予定の長期借入金',
              'IncomeTaxesPayable': '未払法人税',
              'ProvisionForBonuses': '賞与引当金',
              'NoncurrentLiabilities': '固定負債合計',
              'CapitalStock' :'株主資本合計',
              'CapitalSurplus' :'資本剰余金',
              'RetainedEarnings' :'利益剰余金',
              'CapitalStock' :'株主資本合計',
              'ShareholdersEquity': '株主資本合計',
              'ValuationAndTranslationAdjustments': 'その他の包括利益累計額合計',
              'NetAssets': '純資産合計',
              'LiabilitiesAndNetAssets': '負債純資産合計',
              }

f = open('transdict.csv', 'w', encoding='utf-8')
for key in sorted(trans_dict.keys()):
    f.write(key + ',' + trans_dict[key] + '\n')
f.close()
