CUDABINPATH = "/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/bin/"
NVCC = nvcc.exe
NVCCFLAGS = -gencode=arch=compute_60,code=\"sm_60,compute_60\" -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64"

# "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_62,code=\"sm_62,compute_62\" --use-local-env --cl-version 2015 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64" -rdc=true -I./ -I../common/inc -I./ -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\/include" -I../common/inc -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include"  -G   --keep-dir x64\Debug -maxrregcount=0 --ptxas-options=-v --machine 64 --compile -cudart static -Xcompiler "/wd 4819" -g   -DWIN32 -DWIN32 -D_MBCS -D_MBCS -Xcompiler "/EHsc /W3 /nologo /Od /FS /Zi /RTC1 /MTd " -o x64/Debug/cdpHeapsort.cu.obj "C:\Users\sin\Documents\Workspace\CUDA8.0\sortalgorithm\cdpHeapsort.cu"

1>------ Build started: Project: sortalg, Configuration: Debug x64 ------
1>  Compiling CUDA source file cdpHeapsort.cu...
1>  Compiling CUDA source file cdpBitonicSort.cu...
1>  Compiling CUDA source file cu_utils.cu...
1>  Compiling CUDA source file oddevensort.cu...
1>  Compiling CUDA source file main.cu...
1>  Compiling CUDA source file cdpQuicksort.cu...
1>
1>  C:\Users\sin\Documents\Workspace\CUDA8.0\sortalgorithm>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_62,code=\"sm_62,compute_62\" --use-local-env --cl-version 2015 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64" -rdc=true -I./ -I../common/inc -I./ -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\/include" -I../common/inc -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include"  -G   --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart static -Xcompiler "/wd 4819" -g   -DWIN32 -DWIN32 -D_MBCS -D_MBCS -Xcompiler "/EHsc /W3 /nologo /Od /FS /Zi /RTC1 /MTd " -o x64/Debug/cdpHeapsort.cu.obj "C:\Users\sin\Documents\Workspace\CUDA8.0\sortalgorithm\cdpHeapsort.cu"
1>
1>  C:\Users\sin\Documents\Workspace\CUDA8.0\sortalgorithm>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_62,code=\"sm_62,compute_62\" --use-local-env --cl-version 2015 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64" -rdc=true -I./ -I../common/inc -I./ -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\/include" -I../common/inc -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include"  -G   --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart static -Xcompiler "/wd 4819" -g   -DWIN32 -DWIN32 -D_MBCS -D_MBCS -Xcompiler "/EHsc /W3 /nologo /Od /FS /Zi /RTC1 /MTd " -o x64/Debug/cdpBitonicSort.cu.obj "C:\Users\sin\Documents\Workspace\CUDA8.0\sortalgorithm\cdpBitonicSort.cu"
1>
1>  C:\Users\sin\Documents\Workspace\CUDA8.0\sortalgorithm>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_62,code=\"sm_62,compute_62\" --use-local-env --cl-version 2015 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64" -rdc=true -I./ -I../common/inc -I./ -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\/include" -I../common/inc -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include"  -G   --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart static -Xcompiler "/wd 4819" -g   -DWIN32 -DWIN32 -D_MBCS -D_MBCS -Xcompiler "/EHsc /W3 /nologo /Od /FS /Zi /RTC1 /MTd " -o x64/Debug/cu_utils.cu.obj "C:\Users\sin\Documents\Workspace\CUDA8.0\sortalgorithm\cu_utils.cu"
1>
1>  C:\Users\sin\Documents\Workspace\CUDA8.0\sortalgorithm>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_62,code=\"sm_62,compute_62\" --use-local-env --cl-version 2015 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64" -rdc=true -I./ -I../common/inc -I./ -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\/include" -I../common/inc -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include"  -G   --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart static -Xcompiler "/wd 4819" -g   -DWIN32 -DWIN32 -D_MBCS -D_MBCS -Xcompiler "/EHsc /W3 /nologo /Od /FS /Zi /RTC1 /MTd " -o x64/Debug/oddevensort.cu.obj "C:\Users\sin\Documents\Workspace\CUDA8.0\sortalgorithm\oddevensort.cu"
1>
1>  C:\Users\sin\Documents\Workspace\CUDA8.0\sortalgorithm>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_62,code=\"sm_62,compute_62\" --use-local-env --cl-version 2015 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64" -rdc=true -I./ -I../common/inc -I./ -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\/include" -I../common/inc -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include"  -G   --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart static -Xcompiler "/wd 4819" -g   -DWIN32 -DWIN32 -D_MBCS -D_MBCS -Xcompiler "/EHsc /W3 /nologo /Od /FS /Zi /RTC1 /MTd " -o x64/Debug/cdpQuicksort.cu.obj "C:\Users\sin\Documents\Workspace\CUDA8.0\sortalgorithm\cdpQuicksort.cu"
1>
1>  C:\Users\sin\Documents\Workspace\CUDA8.0\sortalgorithm>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_62,code=\"sm_62,compute_62\" --use-local-env --cl-version 2015 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64" -rdc=true -I./ -I../common/inc -I./ -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\/include" -I../common/inc -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include"  -G   --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart static -Xcompiler "/wd 4819" -g   -DWIN32 -DWIN32 -D_MBCS -D_MBCS -Xcompiler "/EHsc /W3 /nologo /Od /FS /Zi /RTC1 /MTd " -o x64/Debug/main.cu.obj "C:\Users\sin\Documents\Workspace\CUDA8.0\sortalgorithm\main.cu"
1>  cdpBitonicSort.cu
1>  cdpQuicksort.cu
1>  cu_utils.cu
1>  main.cu
1>  cdpHeapsort.cu
1>  oddevensort.cu
1>C:/Users/sin/Documents/Workspace/CUDA8.0/sortalgorithm/main.cu(51): warning C4244: 'argument': conversion from 'time_t' to 'unsigned int', possible loss of data
1>C:/Users/sin/Documents/Workspace/CUDA8.0/sortalgorithm/main.cu(165): warning C4018: '<': signed/unsigned mismatch
1>C:/Users/sin/Documents/Workspace/CUDA8.0/sortalgorithm/cdpHeapsort.cu(27): warning C4018: '<': signed/unsigned mismatch
1>
1>  C:\Users\sin\Documents\Workspace\CUDA8.0\sortalgorithm>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe" -dlink -o x64/Debug/sortalg.device-link.obj -Xcompiler "/EHsc /W3 /nologo /Od /Zi /RTC1 /MTd " -L"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64" cudadevrt.lib cudart_static.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib  -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_62,code=sm_62 -G --machine 64 x64/Debug/cdpHeapsort.cu.obj x64/Debug/main.cu.obj x64/Debug/cdpBitonicSort.cu.obj x64/Debug/cu_utils.cu.obj x64/Debug/oddevensort.cu.obj x64/Debug/cdpQuicksort.cu.obj
1>CUDALINK : ptxas warning : .debug_abbrev section not found (target: sm_62)
1>CUDALINK : ptxas warning : .debug_info section not found (target: sm_62)
1>  cudadevrt.lib
1>  cudart_static.lib
1>  kernel32.lib
1>  user32.lib
1>  gdi32.lib
1>  winspool.lib
1>  comdlg32.lib
1>  advapi32.lib
1>  shell32.lib
1>  ole32.lib
1>  oleaut32.lib
1>  uuid.lib
1>  odbc32.lib
1>  odbccp32.lib
1>  cdpHeapsort.cu.obj
1>  main.cu.obj
1>  cdpBitonicSort.cu.obj
1>  cu_utils.cu.obj
1>  oddevensort.cu.obj
1>  cdpQuicksort.cu.obj
1>     Creating library bin\sortalg.lib and object bin\sortalg.exp
1>  template_vs2015.vcxproj -> C:\Users\sin\Documents\Workspace\CUDA8.0\sortalgorithm\bin\sortalg.exe
1>  template_vs2015.vcxproj -> bin\sortalg.pdb (Full PDB)
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========


TARGET = cdpHeapsort.o

%.o: %.cu $(INCLUDES)
	$(CUDABINPATH)$(NVCC) $(NVCCFLAGS) -c $<

%.o: %.cpp $(INCLUDES)
	$(CXX) $(CXXFLAGS) $(INCDIRS) -c $<


#$(TARGET):	$(OBJS) $(INCLUDES)
#	$(NVCC) -o $(TARGET) $(OBJS) $(LIBS)

all: $(TARGET)

clean:
	rm -f $(OBJS) $(TARGET) *~

